-- AlterTable
ALTER TABLE "ConstructionCost" ALTER COLUMN "accuracyLow" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "accuracyHigh" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "UnitPrice" ALTER COLUMN "accuracyLow" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "accuracyHigh" SET DATA TYPE DOUBLE PRECISION;
